version: '3.9'
services:
  app:
    build:
      context: ./ToDoList
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=ToDoList;User Id=ToDoListUser;Password=yourpassword;
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ToDoListUser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ToDoList
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
